### ISSUE TITLE
Build error using node 14 - TypeError

### ISSUE THREAD

**Issue by BryceMehring** [jkuri/rollup-plugin-progress#17]
I'm getting the following error using this plugin with node 14.0.0:

```
(plugin progress) TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (411)
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (411)
    at Object.writeFileSync (fs.js:1380:5)
    at Object.generateBundle (/project/node_modules/rollup-plugin-progress/dist/rollup-plugin-progress.js:62:10)
    at /project/node_modules/rollup/dist/shared/rollup.js:17441:25
```

See https://nodejs.org/api/fs.html#fs_fs_writefilesync_file_data_options on the valid arguments.

**Comment by linningmii** [comment]
I have a PR to fix this type error, waiting for merge.

**Comment by sormy** [comment]
This also happens on fresh NodeJS 12.x

**Comment by breautek** [comment]
> This also happens on fresh NodeJS 12.x

Are you sure? For me this only happens on 14, and is when I first encountered this error myself. Downgrading back to 12.x worked for me. For the record I've tested Node 12.15.0 & Node 12.16.2, both of these versions worked for me.

**Comment by anion155** [comment]
Link #18
